/**
 * Main-thread block while opening a database with a pending migration —
 * inline DatabaseService construction (before) vs the migration worker
 * followed by DatabaseService construction (after). Audit 05, M-6 follow-up.
 *
 * Gated by VARLENS_RUN_MIGRATION_PERF=1:
 *
 *   VARLENS_RUN_MIGRATION_PERF=1 VARLENS_MIGRATION_SUMMARY_ROWS=2000000 \
 *     npx vitest run --project perf tests/perf/startup-migration.perf.test.ts
 *
 * The pending migration is v37 (the cohort keyset index) over a
 * cohort_variant_summary of VARLENS_MIGRATION_SUMMARY_ROWS rows.
 * Results: .planning/code-review/ui-ux-audit-2026-10-06/followups/leftovers-l2/
 */
import { afterAll, describe, expect, it } from 'vitest'
import { copyFileSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { monitorEventLoopDelay, performance } from 'node:perf_hooks'
import { DatabaseService } from '../../src/main/database/DatabaseService'
import {
  migrateSqliteOffThread,
  setMigrationWorkerPathForTesting
} from '../../src/main/database/migrate-off-thread'
import { COHORT_KEYSET_INDEX } from '../../src/shared/sql/cohort-keyset'
import { bundleWorker } from '../utils/bundle-worker'

const SHOULD_RUN = process.env.VARLENS_RUN_MIGRATION_PERF === '1'
const ROWS = Number(process.env.VARLENS_MIGRATION_SUMMARY_ROWS ?? '500000')
const OUT_DIR = resolve(
  process.cwd(),
  '.planning/code-review/ui-ux-audit-2026-10-06/followups/leftovers-l2'
)

interface Row {
  path: string
  wallMs: number
  maxBlockMs: number
}

async function measure(path: string, fn: () => Promise<unknown> | unknown): Promise<Row> {
  const histogram = monitorEventLoopDelay({ resolution: 5 })
  histogram.enable()
  let last = performance.now()
  let maxGap = 0
  const heartbeat = setInterval(() => {
    const now = performance.now()
    maxGap = Math.max(maxGap, now - last)
    last = now
  }, 5)
  await new Promise((r) => setTimeout(r, 20))
  const started = performance.now()
  await fn()
  const wallMs = performance.now() - started
  await new Promise((r) => setTimeout(r, 30))
  clearInterval(heartbeat)
  histogram.disable()
  return {
    path,
    wallMs: Math.round(wallMs),
    maxBlockMs: Math.round(Math.max(maxGap, histogram.max / 1e6))
  }
}

function seedPendingV36(path: string): void {
  const service = new DatabaseService(path)
  const db = service.database
  const insert = db.prepare(
    `INSERT INTO cohort_variant_summary (chr, pos, ref, alt, variant_type, genome_build,
       carrier_count, het_count, hom_count, variant_key)
     VALUES (?, ?, 'A', 'G', 'snv', 'GRCh38', ?, 0, 0, '')`
  )
  db.transaction(() => {
    for (let i = 0; i < ROWS; i++) insert.run(String((i % 22) + 1), i, (i % 20) + 1)
  })()
  db.exec(`DROP INDEX ${COHORT_KEYSET_INDEX}`)
  db.pragma('user_version = 36')
  db.pragma('wal_checkpoint(TRUNCATE)')
  service.close()
}

describe.skipIf(!SHOULD_RUN)('startup migration: main thread vs worker', () => {
  const rows: Row[] = []
  const dir = SHOULD_RUN ? mkdtempSync(join(tmpdir(), 'varlens-migration-perf-')) : ''

  afterAll(() => {
    if (!SHOULD_RUN) return
    setMigrationWorkerPathForTesting(undefined)
    rmSync(dir, { recursive: true, force: true })
    mkdirSync(OUT_DIR, { recursive: true })
    const meta = { summaryRows: ROWS, node: process.version, date: new Date().toISOString() }
    writeFileSync(
      join(OUT_DIR, `startup-migration-${ROWS}.json`),
      JSON.stringify({ meta, rows }, null, 2) + '\n'
    )
    writeFileSync(
      join(OUT_DIR, `startup-migration-${ROWS}.md`),
      [
        '# Opening a database with a pending migration — main thread vs worker',
        '',
        `Pending migration: v37 (cohort keyset index) over ${ROWS.toLocaleString('en-US')} cohort_variant_summary rows, ${meta.node}, ${meta.date}.`,
        'Generated by `tests/perf/startup-migration.perf.test.ts`. "Max block" = longest event-loop stall of the calling (Electron main) thread.',
        '',
        '| Path | Wall ms | Max main-thread block ms |',
        '|---|---:|---:|',
        ...rows.map((r) => `| ${r.path} | ${r.wallMs} | ${r.maxBlockMs} |`)
      ].join('\n') + '\n'
    )
  })

  it('opens the database', async () => {
    setMigrationWorkerPathForTesting(await bundleWorker('src/main/workers/migration-worker.ts'))
    const template = join(dir, 'template.db')
    seedPendingV36(template)
    const before = join(dir, 'before.db')
    const after = join(dir, 'after.db')
    copyFileSync(template, before)
    copyFileSync(template, after)

    rows.push(
      await measure('before: DatabaseService migrates inline on main', () =>
        new DatabaseService(before).close()
      )
    )
    rows.push(
      await measure('after: migration worker, then DatabaseService', async () => {
        const result = await migrateSqliteOffThread(after)
        expect(result).toMatchObject({ ran: true, fromVersion: 36, toVersion: 37 })
        new DatabaseService(after).close()
      })
    )
    expect(rows[1].maxBlockMs).toBeLessThan(rows[0].maxBlockMs)
  }, 3_600_000)
})
